### ISSUE TITLE
[Website] content updates before CA World

### ISSUE THREAD

**Issue by riley** [mineral-ui/mineral-ui#427]
As a visitor to mineral-ui.com post CA world, I would like to see a polished website with most of the expected trappings.

AC:
- [x] different `<title>` element for each page [#433](https://github.com/mineral-ui/mineral-ui/pull/433)
- [x] `lang="en-US"` on the `<html>` element [#433](https://github.com/mineral-ui/mineral-ui/pull/433)
- [x] expand some acronyms e.g. RTL where needed [#436](https://github.com/mineral-ui/mineral-ui/pull/436)
- [x] better explanation of difference between `title` and `alt` attributes for Icons? [#436](https://github.com/mineral-ui/mineral-ui/pull/436)
- [x] icon category links? [#436](https://github.com/mineral-ui/mineral-ui/pull/436)
- [x] embellish copy on first Link example [#436](https://github.com/mineral-ui/mineral-ui/pull/436)
- [x] re-add example h2 above component examples [#436](https://github.com/mineral-ui/mineral-ui/pull/436)
- [x] rename all the first examples to not be "Example" [#436](https://github.com/mineral-ui/mineral-ui/pull/436)

**Comment by wendyjm** [comment]
Revisit best practices and do/don't vs. always/never (if never is needed at all)
