### ISSUE TITLE
Legacy React lifecycle migration

### ISSUE THREAD

**Issue by brentertz** [mineral-ui/mineral-ui#652]
As a mineral-ui developer, I would like to migrate components from legacy React lifecycle methods, in order to ensure future compatibility.

**AC:**

* [x] Mineral components, excluding Table; Parent of #763
* [x] Table component; Parent of #764
* [ ] 3rd party dependencies; Parent of #765

**Other Considerations:**

* Use the [polyfill](https://github.com/reactjs/react-lifecycles-compat) to make the new lifecycles work with older versions of React
* Use jest:react script to test in different React versions
* https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
* https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html
* https://reactjs.org/docs/strict-mode.html
* https://github.com/reactjs/react-lifecycles-compat
* Some of our dependencies, e.g. emotion, still rely on legacy lifecycle methods.  They will need to migrate prior to us being able to be completely free of them.
