### ISSUE TITLE
Emotion migration

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#692]
_The Glamorous project has been deprecated and the suggested path forward is to migrate to Emotion._

https://github.com/paypal/glamorous/issues/419

### Initial investigation

Emotion "may" be able to do all of the things that Glamorous can do, but not with the same API and not out of the box.

**API Docs**
  * [Glamorous](https://glamorous.rocks/api/)
  * [Emotion](https://emotion.sh/docs)
    * [Stylis](https://stylis.js.org/) - Emotion uses this internally

**Performance**
  * Emotion is reported to be both smaller and faster than Glamorous
  * Here are some CSS-IN-JS benchmarks - https://github.com/A-gambit/CSS-IN-JS-Benchmarks/blob/master/RESULT.md

----
**AC:**

* [x] Site renders properly and without warnings
* [x] Components render properly and without warnings
* [x] Migration documentation created for consumers

**Tasks:**

* [x] Remove Glamorous dependencies
  * [x] `glamor` is needed as a dev dependency until the `simulate` helper usages have been removed
  * [x] `glamorous`, `jest-glamor-react`
  * [x] `css` prop is not compatible with `babel-plugin-transform-react-inline-elements`.  We have opted to NOT use `babel-plugin-emotion`, so this can remain intact.
* [x] Add new Emotion dependencies
  * `emotion`, `react-emotion`, `emotion-theming`, `jest-emotion`, `eslint-plugin-emotion`, `recompose`
* [x] Update `createThemedComponent`
* [x] Update `createStyledComponent`
  * [x] Css label identifiers in development only
  * [x] Verify preset filtered props
* [x] Update `ThemeProvider`
* [x] Update `withTheme`
* [x] Implement replacement for glamorous `withProps`.
* [x] Configure `jest-emotion` snapshot serializer
* [x] Update install documentation
* [x] Update examples and other documentation
* [x] Remove or reimplement glamor `simulate`.  See https://github.com/emotion-js/emotion/issues/666 This has been removed for now.
* [x] [Emotion uses WeakMap](https://github.com/emotion-js/emotion/blob/master/packages/create-emotion/src/index.js#L166) so we would potentially need to document the need for users to polyfill this in their apps.  WeakMap is mostly supported in IE11 though and as far as I can tell by their usage, it should work.
  * Tested website in IE11 VM with polyfills disabled via `useBuiltins: false` in `babelrc.js`.  No problemos.
* [x] Drop support for `css` prop until Emotion implements it without a babel plugin.
* [x] There are a couple places in the website that use glamor `css` directly.  `import { css } from 'glamor';` These need updated. - `Loading.js` and `NotFound.js`
* [x] React 16.4 adds support for pointer events - add them to `reactProps.js`
* [x] Can remove no longer needed "inert" styles inside of several createStyledComponent calls that were used to circumvent glamorous cache issue.  These are difficult to search for since the styles used may not always be the same.  They can be removed incrementally in the future as we come across them.  Mineral developers should note that they are no longer needed.
* [x] Update to new version of Emotion containing our `shouldForwardProp` composition fix, once released.
